# --------------------------------------------------
#  BASIC SITE INFO
# --------------------------------------------------
title: Meichao Song
tagline: Personal academic website of Meichao Song, PhD Student at Emory University.
description: Personal website of Meichao Song, PhD Student in the Department of Political Science at Emory University.

url: https://meichaopolisci.github.io/MeichaoCV202606
baseurl: /MeichaoCV202606

# --------------------------------------------------
#  AUTHOR / PROFILE DATA
# --------------------------------------------------
owner:
  name: Meichao Song
  email: meichao.song@emory.edu
  github: MeichaoPoliSci
  scholar: https://scholar.google.com/citations?user=Ia2a43MAAAAJ&hl=zh-TW
  linkedin: meichao-s-191a51279/
  twitter: MeichaoSon31048
  bluesky: meichao.bsky.social


# --------------------------------------------------
#  TOP NAVIGATION BAR
# --------------------------------------------------
links:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: Resources
    url: /resources/
  - title: CV
    url: /cv/


# --------------------------------------------------
#  BUILD & RENDERING OPTIONS
# --------------------------------------------------
timezone: America/Chicago
future: true
highlighter: rouge

permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude:
  - "backup"
  - "lib"
  - "config.rb"
  - "Capfile"
  - "config"
  - "log"
  - "Rakefile"
  - "Rakefile.rb"
  - "tmp"
  - "less"
  - "minimal-mistakes.sublime-project"
  - "minimal-mistakes.sublime-workspace"

plugins:
  - jekyll-feed
  - jekyll-sitemap
